name: Build and deploy container to Azure Web App - godata-bak-ai

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_IMAGE: camd0204/godata-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_55C06848E28545568133964932C98A85 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D2C4322A4A7142E4827D6C71DB54FD81 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BC42C1A57A7144B3900FDA181324B139 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'godata-bak-ai'
          images: '${{ env.DOCKER_IMAGE }}:${{ github.sha }}'
          